spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/student?characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver